# Generated by Django 5.1.6 on 2025-02-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('author', models.CharField(max_length=45)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(default='default.png', upload_to='thumbnails/')),
            ],
        ),
    ]
